version: "3.8"

services:
  app:
    build: ./app
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Para o container identificar as alterações
      - NODE_ENV=development
      - VITE_PORT=5173
    command: ["npm", "run", "dev", "--", "--host"]

  api:
    build: ./api
    ports:
      - "3333:3000"
    env_file:
      - ./api/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # Para o container identificar as alterações
    volumes:
      - ./api:/api
      - /api/node_modules
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - api
